[package]
name = "tabforge-audio"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tabforge-core = { workspace = true }
symphonia = { workspace = true }
rustfft = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
